CREATE TABLE celebration_mariage (
                                     id INT8 PRIMARY KEY,
                                     id_utilisateur_demande INT8 NULL,
                                     code_demande VARCHAR(100) NOT NULL DEFAULT '',
                                     nom_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     telephone_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     date_naiss_epoux DATE NOT NULL,
                                     lieu_naiss_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     profession_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     nom_pere_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_pere_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     nom_mere_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_mere_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     domicile_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     type_piece_ident_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     chem_piece_ident_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     certif_residence_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     nom_temoin_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_temoin_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     profession_temoin_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     domicile_temoin_epoux VARCHAR(100) NOT NULL DEFAULT '',
                                     type_piece_ident_temoin_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     chem_piece_ident_temoin_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     photo_ident_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     situation_matri_epoux VARCHAR(255) NOT NULL DEFAULT '',
                                     nom_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     telephone_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     date_naiss_epouse DATE NOT NULL,
                                     lieu_naiss_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     profession_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     nom_pere_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_pere_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     nom_mere_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_mere_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     domicile_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     type_piece_ident_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     chem_piece_ident_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     certif_residence_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     nom_temoin_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     prenoms_temoin_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     profession_temoin_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     domicile_temoin_epouse VARCHAR(100) NOT NULL DEFAULT '',
                                     type_piece_ident_temoin_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     chem_piece_ident_temoin_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     photo_ident_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     situation_matri_epouse VARCHAR(255) NOT NULL DEFAULT '',
                                     date_rendez_vous TIMESTAMP WITHOUT TIME ZONE,
                                     regime VARCHAR(50) DEFAULT 'COMMUNAUTE_BIEN' CHECK (regime IN ('COMMUNAUTE_BIEN', 'SEPARATION_BIEN')),
                                     statut VARCHAR(50) DEFAULT 'NON_DEMARRE' CHECK (statut IN ('NON_DEMARRE', 'EN_COURS', 'REJETE', 'VALIDE', 'ANNULE', 'TERMINE')),
                                     role_demandeur VARCHAR(50) DEFAULT 'EPOUX' CHECK (role_demandeur IN ('EPOUX', 'EPOUSE', 'AMI', 'PARENT', 'TUTEUR')),
                                     code_registre VARCHAR(50) NOT NULL DEFAULT '',
                                     id_registre INT8 NULL,
                                     montant INT8 DEFAULT 0,
                                     id_etape_active INT DEFAULT 0,
                                     delai_etape_active INT8 DEFAULT 0,
                                     nom_etape_active VARCHAR(50),
                                     create_at TIMESTAMP,
                                     create_by VARCHAR(255),
                                     update_at TIMESTAMP,
                                     update_by VARCHAR(255),
                                     version INT8 NOT NULL DEFAULT 0
);

CREATE SEQUENCE celebration_mariage_id_seq INCREMENT BY 50 START 1;
ALTER TABLE celebration_mariage ALTER COLUMN id SET DEFAULT nextval('celebration_mariage_id_seq');
